"""Original Cal-QL paper's own offline-to-online design, built on the shared shell.

``Off2OnCalQL`` adds no behavior on top of ``_CalQLRolloutTrainingShell``
beyond a construction-time preset: no warmup by default (unlike ``WSRL``),
offline data retained and mixed throughout online fine-tuning by default, and
the CQL/Cal-QL regularizer retained online by default. See Nakamoto et al.
2023. ``initial_training_phase`` is still accepted (for interface parity with
the shared off2on runner) but left unused by the ``calql`` CLI preset.
"""
from __future__ import annotations

from typing import Any, Literal, Optional, Sequence

import torch

from rl_garden.algorithms.calql import _CalQLRolloutTrainingShell
from rl_garden.common.logger import Logger
from rl_garden.common.training_phase import InitialTrainingPhase
from rl_garden.encoders.combined import ImageEncoderFactory


class Off2OnCalQL(_CalQLRolloutTrainingShell):
    """Cal-QL offline pretraining + online fine-tuning, no warmup."""

    _compatible_checkpoint_algorithms = ("Off2OnCalQL", "WSRL", "CalQL", "CQL")

    def __init__(
        self,
        env: Any,
        eval_env: Optional[Any] = None,
        # Buffer and training
        buffer_size: int = 1_000_000,
        buffer_device: str = "cuda",
        learning_starts: int = 4_000,
        batch_size: int = 256,
        gamma: float = 0.99,
        tau: float = 0.005,
        training_freq: int = 64,
        utd: float = 1.0,
        bootstrap_at_done: str = "always",
        # Optimizers
        policy_lr: float = 1e-4,
        q_lr: float = 3e-4,
        alpha_lr: float = 1e-4,
        cql_alpha_lr: float = 3e-4,
        policy_frequency: int = 1,
        target_network_frequency: int = 1,
        weight_decay: float = 0.0,
        use_adamw: bool = False,
        lr_schedule: Literal["constant", "linear_warmup", "warmup_cosine"] = "constant",
        lr_warmup_steps: int = 0,
        lr_decay_steps: int = 0,
        lr_min_ratio: float = 0.0,
        grad_clip_norm: Optional[float] = None,
        use_compile: bool = False,
        compile_mode: Literal["default", "reduce-overhead", "max-autotune"] = "default",
        # Entropy
        ent_coef: float | str = "auto",
        target_entropy: float | str = "auto",
        backup_entropy: bool = False,
        # Network architecture
        net_arch: Optional[Sequence[int] | dict[str, Sequence[int]]] = None,
        actor_hidden_dims: Optional[Sequence[int]] = None,
        critic_hidden_dims: Optional[Sequence[int]] = None,
        actor_use_layer_norm: bool = True,
        critic_use_layer_norm: bool = True,
        actor_use_group_norm: bool = False,
        critic_use_group_norm: bool = False,
        num_groups: int = 32,
        actor_dropout_rate: Optional[float] = None,
        critic_dropout_rate: Optional[float] = None,
        kernel_init: Optional[str] = None,
        backbone_type: Literal["mlp", "mlp_resnet"] = "mlp",
        std_parameterization: Literal["exp", "uniform"] = "exp",
        # Q-ensemble (REDQ)
        n_critics: int = 10,
        critic_subsample_size: Optional[int] = 2,
        actor_feature_dim: Optional[int] = None,
        critic_spatial_emb_dim: int = 1024,
        # CQL parameters
        use_cql_loss: bool = True,
        cql_n_actions: int = 10,
        cql_alpha: float = 5.0,
        cql_autotune_alpha: bool = False,
        cql_alpha_lagrange_init: float = 1.0,
        cql_target_action_gap: float = 1.0,
        cql_importance_sample: bool = True,
        cql_max_target_backup: bool = True,
        cql_temp: float = 1.0,
        cql_clip_diff_min: float = float("-inf"),
        cql_clip_diff_max: float = float("inf"),
        cql_action_sample_method: str = "uniform",
        # Cal-QL parameters
        use_calql: bool = True,
        calql_bound_random_actions: bool = False,
        # Dict observation encoding
        image_encoder_factory: Optional[ImageEncoderFactory] = None,
        image_keys: Optional[tuple[str, ...]] = None,
        state_key: Optional[str] = None,
        use_proprio: Optional[bool] = None,
        proprio_latent_dim: Optional[int] = None,
        image_fusion_mode: Optional[str] = None,
        enable_stacking: Optional[bool] = None,
        detach_encoder_on_actor: bool = True,
        # Off2on phase control
        use_td_loss: bool = True,
        online_cql_alpha: float = 5.0,
        online_use_cql_loss: bool = True,
        offline_sampling: Literal["with_replace", "without_replace"] = "with_replace",
        # Sparse-reward MC
        sparse_reward_mc: bool = False,
        sparse_negative_reward: float = 0.0,
        success_threshold: float = 0.5,
        # General
        policy_kwargs: Optional[dict[str, Any]] = None,
        seed: int = 1,
        device: str | torch.device = "auto",
        logger: Optional[Logger] = None,
        std_log: bool = True,
        log_freq: int = 1_000,
        eval_freq: int = 25,
        num_eval_steps: int = 50,
        checkpoint_dir: Optional[str] = None,
        checkpoint_freq: int = 0,
        save_replay_buffer: bool = False,
        save_final_checkpoint: bool = True,
        initial_training_phase: Optional[InitialTrainingPhase] = None,
    ) -> None:
        self._configure_observation_kwargs(
            env,
            image_encoder_factory=image_encoder_factory,
            image_keys=image_keys,
            state_key=state_key,
            use_proprio=use_proprio,
            proprio_latent_dim=proprio_latent_dim,
            image_fusion_mode=image_fusion_mode,
            enable_stacking=enable_stacking,
            detach_encoder_on_actor=detach_encoder_on_actor,
        )

        super().__init__(
            env=env,
            eval_env=eval_env,
            buffer_size=buffer_size,
            buffer_device=buffer_device,
            learning_starts=learning_starts,
            batch_size=batch_size,
            gamma=gamma,
            tau=tau,
            training_freq=training_freq,
            utd=utd,
            bootstrap_at_done=bootstrap_at_done,
            policy_lr=policy_lr,
            q_lr=q_lr,
            alpha_lr=alpha_lr,
            cql_alpha_lr=cql_alpha_lr,
            policy_frequency=policy_frequency,
            target_network_frequency=target_network_frequency,
            weight_decay=weight_decay,
            use_adamw=use_adamw,
            lr_schedule=lr_schedule,
            lr_warmup_steps=lr_warmup_steps,
            lr_decay_steps=lr_decay_steps,
            lr_min_ratio=lr_min_ratio,
            grad_clip_norm=grad_clip_norm,
            use_compile=use_compile,
            compile_mode=compile_mode,
            ent_coef=ent_coef,
            target_entropy=target_entropy,
            backup_entropy=backup_entropy,
            net_arch=net_arch,
            actor_hidden_dims=actor_hidden_dims,
            critic_hidden_dims=critic_hidden_dims,
            actor_use_layer_norm=actor_use_layer_norm,
            critic_use_layer_norm=critic_use_layer_norm,
            actor_use_group_norm=actor_use_group_norm,
            critic_use_group_norm=critic_use_group_norm,
            num_groups=num_groups,
            actor_dropout_rate=actor_dropout_rate,
            critic_dropout_rate=critic_dropout_rate,
            kernel_init=kernel_init,
            backbone_type=backbone_type,
            std_parameterization=std_parameterization,
            n_critics=n_critics,
            critic_subsample_size=critic_subsample_size,
            actor_feature_dim=actor_feature_dim,
            critic_spatial_emb_dim=critic_spatial_emb_dim,
            use_cql_loss=use_cql_loss,
            cql_n_actions=cql_n_actions,
            cql_alpha=cql_alpha,
            cql_autotune_alpha=cql_autotune_alpha,
            cql_alpha_lagrange_init=cql_alpha_lagrange_init,
            cql_target_action_gap=cql_target_action_gap,
            cql_importance_sample=cql_importance_sample,
            cql_max_target_backup=cql_max_target_backup,
            cql_temp=cql_temp,
            cql_clip_diff_min=cql_clip_diff_min,
            cql_clip_diff_max=cql_clip_diff_max,
            cql_action_sample_method=cql_action_sample_method,
            use_calql=use_calql,
            calql_bound_random_actions=calql_bound_random_actions,
            sparse_reward_mc=sparse_reward_mc,
            sparse_negative_reward=sparse_negative_reward,
            success_threshold=success_threshold,
            use_td_loss=use_td_loss,
            online_cql_alpha=online_cql_alpha,
            online_use_cql_loss=online_use_cql_loss,
            offline_sampling=offline_sampling,
            policy_kwargs=policy_kwargs,
            seed=seed,
            device=device,
            logger=logger,
            std_log=std_log,
            log_freq=log_freq,
            eval_freq=eval_freq,
            num_eval_steps=num_eval_steps,
            checkpoint_dir=checkpoint_dir,
            checkpoint_freq=checkpoint_freq,
            save_replay_buffer=save_replay_buffer,
            save_final_checkpoint=save_final_checkpoint,
            initial_training_phase=initial_training_phase,
        )
